### ISSUE TITLE
Nokia NAT not decoding properly

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/go-nfdump#13]
Hi Pete,

I just tried out new extensions for Nokia NAT events, but `NokiaNat()` and `NokiaNatString()` seems not to be working properly.

`NokiaNat()` is returning always `nil` while `NokiaNatString()` is returning empty string.

Sample file is the same that originated the issue in `nfdump` main repo, but I'm attaching it anyways.

[nokia_nat44.sample.zip](https://github.com/user-attachments/files/15534971/nokia_nat44.sample.zip)

**Comment by phaag** [comment]
@gabrielmocan - that file does not contain any collected Nokia extensions. Therefore they are nil.
Are you sure, to have replaced the collector from master branch?

**Comment by gabrielmocan** [comment]
@phaag oh, I see, so these extensions will only be available for nfcapd files created _after_ https://github.com/phaag/nfdump/issues/533, right?

**Comment by phaag** [comment]
yes - nfcapd simply skips elements it does not know. Therefore only newly collected data contains those elements.

**Comment by gabrielmocan** [comment]
Understood, my bad then!
