### ISSUE TITLE
Quick way to determine if a record is v4 or v6

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/go-nfdump#3]
I was thinking of something like record.Type() to tell if current record being processed is v4 or v6. I want to store v4/v6 records in different structs.

**Comment by phaag** [comment]
I would propose `record.IsIPv4()` and `record.IsIPv6()`. We could introduce `record.Type()` as well, but would reserve it for the type of record, such as `Event`, `Netflow`, `Sflow`

**Comment by gabrielmocan** [comment]
This is getting awesome! Insane gains compared to calling CLI in code. Thanks @phaag

**Comment by phaag** [comment]
Happy, it works!!
