### ISSUE TITLE
Make use of sampling rate (if sent by exporter)

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/go-nfdump#4]
Hi Pete, I was wondering how can we reproduce nfdump's CLI behavior of using exporter's sample rate factor in dumping. Can we retrieve this value as of now?

**Comment by phaag** [comment]
You mean, the sampler and exporter information?

**Comment by gabrielmocan** [comment]
Yes, the sampling interval. I see there is available in the EXsamplerInfo extension, but still not implemented, right?

**Comment by phaag** [comment]
It's a bit more complicated than that, as records only contain references to exporters and samplers. Let's do it in two steps. 
First add the exporter, then the sampler.

**Comment by phaag** [comment]
Can you try with the latest main repo?

**Comment by gabrielmocan** [comment]
It works like a charm. Thanks Pete.
