### ISSUE TITLE
sflow records not being processed

### ISSUE THREAD

**Issue by gabrielmocan** [phaag/go-nfdump#7]
Hi Pete, I'm having issue to read the sflow capture. I've attached a sample to your e-mail.

nfdump CLI's read it all right, go-nfdump reports 0 records.

**Comment by phaag** [comment]
I can not confirm your findings. The sample reader processes both files with the same number of flows, as cli nfdump.
I would be surprised as there is no difference in the data format. Slow and netflow differ only in the nfversion field.

**Comment by gabrielmocan** [comment]
You're right @phaag, my samples doesn't have nextHop information, so nil checking was making the result 0.

Sorry about that, I'm closing this issue.
